### ISSUE TITLE
exception when no pymoca_cache file available. please check on existence first

### ISSUE THREAD

**Issue by gijsber** [pymoca/pymoca#165]
If you do not have pymoca_cache file available yet, you do get a stack dump.
Please check for existence of the file

Traceback (most recent call last):
  File "D:\RTC-Tools2.2\gprework\venv\lib\site-packages\pymoca\backends\casadi\api.py", line 422, in transfer_model
    return load_model(model_folder, model_name, compiler_options)
  File "D:\RTC-Tools2.2\gprework\venv\lib\site-packages\pymoca\backends\casadi\api.py", line 261, in load_model
    cache_mtime = os.path.getmtime(db_file)
  File "d:\Python363\lib\genericpath.py", line 55, in getmtime
    return os.stat(filename).st_mtime
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'D:\\RTC-Tools2.2\\gprework\\nhi4\\src\\..\\cases\\nationaal_v3_3h\\model\\DistributionModel.pymoca_cache

**Comment by gijsber** [comment]
User error :-)
