### ISSUE TITLE
CasADi: a constant is allowed to be a canonical variable but it is not handled properly

### ISSUE THREAD

**Issue by PeterRabbit95** [pymoca/pymoca#218]
The problem is well explained in the following example:

## Constant

If `c` is a constant then it may become a canonical variable with z as an alias but it will raise an error.

```modelica
model ConstantAlias

Real x;
Real z;
constant Real c=0;

equation

der(x) = c;
z = c;

end ConstantAlias;
```

```python
options = {'detect_aliases': True}
model = transfer_model(model_folder, 'ConstantAlias', options)
```

```
INFO:pymoca:Detecting aliases
Traceback (most recent call last):
  File "/home/pietro/anaconda3/envs/pymocaExp/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3331, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-d427935174b8>", line 32, in <module>
    model = transfer_model(model_folder, 'ConstantAlias', options)
  File "/home/pietro/Desktop/Thesis/git/pymoca/src/pymoca/backends/casadi/api.py", line 477, in transfer_model
    return _compile_model(model_folder, model_name, compiler_options)
  File "/home/pietro/Desktop/Thesis/git/pymoca/src/pymoca/backends/casadi/api.py", line 119, in _compile_model
    model.simplify(compiler_options)
  File "/home/pietro/Desktop/Thesis/git/pymoca/src/pymoca/backends/casadi/model.py", line 844, in simplify
    canonical_state = all_states[canonical]
KeyError: 'c'
```

## Parameter 

If `c` is a parameter then there are no problems:

```modelica
model ParameterAlias

Real x;
Real z;
parameter Real c=0;

equation

der(x) = c;
z = c;

end ParameterAlias;
```

```python
options = {'detect_aliases': True}
model = transfer_model(model_folder, 'ParameterAlias', options)
```

**Comment by PeterRabbit95** [comment]
Imho there are 3 solutions to the problem (in order of preference):
- We do not allow constants to become aliases
- We add the constants to all_states
- We oblige a call to `replace_constant_values` and `replace_constant_expressions` before `detect_aliases`

**Comment by jackvreeken** [comment]
Because constants are Variables like any other (particularly like parameters in my opinion), option 2 makes the most sense to me. At least then we end up with a similar situation for both constants and parameters, where the algebraic state `z` is just an alias of parameter/constant `c`.

Something like this should cover it then:
```diff
diff --git a/src/pymoca/backends/casadi/model.py b/src/pymoca/backends/casadi/model.py
index 8b788f4..d790fe4 100644
--- a/src/pymoca/backends/casadi/model.py
+++ b/src/pymoca/backends/casadi/model.py
@@ -767,6 +767,7 @@ class Model:
             alg_states = OrderedDict([(s.symbol.name(), s) for s in self.alg_states])
             inputs = OrderedDict([(s.symbol.name(), s) for s in self.inputs])
             parameters = OrderedDict([(s.symbol.name(), s) for s in self.parameters])
+            constants = OrderedDict([(s.symbol.name(), s) for s in self.constants])

             all_states = OrderedDict()
             all_states.update(states)
@@ -774,9 +775,10 @@ class Model:
             all_states.update(alg_states)
             all_states.update(inputs)
             all_states.update(parameters)
+            all_states.update(constants)

             # For now, we only eliminate algebraic states.
-            do_not_eliminate = set(list(der_states) + list(states) + list(inputs) + list(parameters))
+            do_not_eliminate = set(list(der_states) + list(states) + list(inputs) + list(parameters) + list(constants))

             # When doing a `detect_aliases` pass multiple times, we have to avoid
             # handling aliases we already handled before as their states no longer
````

**Comment by PeterRabbit95** [comment]
Looks good to me. I was not sure if you wanted to keep the parameters conceptually separated from the constants.
