### ISSUE TITLE
Using OpenModelica model with Modelica dependencies with CasADi

### ISSUE THREAD

**Issue by FreyJo** [pymoca/pymoca#233]
Hi,

We are currently trying to load an OpenModelica model with pymoca to use it with CasADi.
It is a fairly simple model that consists of some Modelica blocks connected via the GUI of OpenModelica.
We tried a few approaches that failed with different errors, see the Code below.
[To reproduce the errors, please download this file which contains the Python script and the model.](https://cloud.syscop.de/index.php/s/Nfzir97jdjsGgR6)

- export the model as mentioned in OpenModelica Docu: `omc -g=Optimica --simCodeTarget=XML Model.mo`
- using transfer_model
- using transfer_model on a total model (exported from OpenModelica using SaveTotal)
- exporting XML from OpenModelica and parsing with pymoca
- dumping the total model to XML DAE and parsing with pymoca
- parsing the XML of a total model
- modifying that XML to avoid warnings.

We would highly appreciate any hints on how this can be done.
Ressources on the limitations which Modelica models can be used with CasADi would also be very helpful.

Best regards,
Jonathan

```
import os
from OMPython import OMCSessionZMQ
from pymoca.parser import parse as parse_mo
from pymoca.backends.xml import parser as parse_xml
from pymoca.backends.xml.generator import generate as generate_xml
from pymoca.backends.casadi.api import transfer_model

#%% Approach 0: export OpenModelica model as suggested in OpenModelica Docu Section 12.5.1
# https://openmodelica.org/doc/OpenModelicaUsersGuide/OpenModelicaUsersGuide-latest.pdf
model_path = 'openmodelica_model'
os.chdir(model_path)
os.system("omc -g=Optimica --simCodeTarget=XML SysSim_ECar.mo")


# Error processing file: SysSim_ECar.mo
# [/usr/lib/omlibrary/Modelica 3.2.3/Mechanics/MultiBody/Examples/Constraints.mo:20:24-20:33:writable] Error: No viable alternative near token: Prismatic
# Notification: Skipped loading package Modelica (3.2.3,default) using MODELICAPATH /usr/bin/../lib/omlibrary:/home/oj/.openmodelica/libraries/ (uses-annotation may be wrong).
# [.../issue_pymoca/openmodelica_model/SysSim_ECar.mo:2:3-3:113:writable] Error: Class Modelica.Mechanics.Translational.Components.Mass not found in scope SysSim_ECar.
# Error: Error occurred while flattening model SysSim_ECar

# Error encountered! Exiting...
# Please check the error message and the flags.

#%% Approach 1: use pymoca transfer_model -> Trying to set unknown symbol property m
model_path = 'openmodelica_model'
os.chdir(model_path)
model = transfer_model('./', 'SysSim_ECar', {})

#   File "env/lib/python3.8/site-packages/pymoca/backends/casadi/api.py", line 485, in transfer_model
#     return _compile_model(model_folder, model_name, compiler_options)
#   File "env/lib/python3.8/site-packages/pymoca/backends/casadi/api.py", line 119, in _compile_model
#     model = generator.generate(tree, model_name, compiler_options)
#   File "env/lib/python3.8/site-packages/pymoca/backends/casadi/generator.py", line 960, in generate
#     flat_tree = flatten(ast_tree, component_ref)
#   File "env/lib/python3.8/site-packages/pymoca/tree.py", line 1077, in flatten
#     flat_class = flatten_class(orig_class)
#   File "env/lib/python3.8/site-packages/pymoca/tree.py", line 869, in flatten_class
#     flat_class = flatten_symbols(instance_tree)
#   File "env/lib/python3.8/site-packages/pymoca/tree.py", line 553, in flatten_symbols
#     apply_symbol_modifications(flat_class, class_)
#   File "env/lib/python3.8/site-packages/pymoca/tree.py", line 791, in apply_symbol_modifications
#     w.walk(SymbolModificationApplier(node, scope), node)
#   File "env/lib/python3.8/site-packages/pymoca/tree.py", line 191, in walk
#     self.handle_walk(listener, tree.__dict__[child_name])
#   File "env/lib/python3.8/site-packages/pymoca/tree.py", line 208, in handle_walk
#     self.handle_walk(listener, tree[k])
#   File "env/lib/python3.8/site-packages/pymoca/tree.py", line 205, in handle_walk
#     self.walk(listener, tree)
#   File "env/lib/python3.8/site-packages/pymoca/tree.py", line 195, in walk
#     getattr(listener, 'exit' + name)(tree)
#   File "env/lib/python3.8/site-packages/pymoca/tree.py", line 775, in exitSymbol
#     modify_symbol(tree, self.scope)
#   File "env/lib/python3.8/site-packages/pymoca/tree.py", line 749, in modify_symbol
#     raise Exception("Trying to set unknown symbol property {}".format(argument.component.name))
# Exception: Trying to set unknown symbol property m


#%% Approach 2: use pymoca transfer_model on total model -> unexpected .mo Syntax 
model_path = 'total_model'
os.chdir(model_path)

model = transfer_model('./', 'Total_Car', {})

#   File "env/lib/python3.8/site-packages/pymoca/backends/casadi/api.py", line 485, in transfer_model
#     return _compile_model(model_folder, model_name, compiler_options)
#   File "env/lib/python3.8/site-packages/pymoca/backends/casadi/api.py", line 112, in _compile_model
#     tree = parser.parse(f.read())
#   File "env/lib/python3.8/site-packages/pymoca/parser.py", line 770, in parse
#     parse_walker.walk(ast_listener, parse_tree)
#   File "env/lib/python3.8/site-packages/antlr4/tree/Tree.py", line 151, in walk
#     self.walk(listener, child)
#   File "env/lib/python3.8/site-packages/antlr4/tree/Tree.py", line 151, in walk
#     self.walk(listener, child)
#   File "env/lib/python3.8/site-packages/antlr4/tree/Tree.py", line 151, in walk
#     self.walk(listener, child)
#   [Previous line repeated 19 more times]
#   File "env/lib/python3.8/site-packages/antlr4/tree/Tree.py", line 152, in walk
#     self.exitRule(listener, t)
#   File "env/lib/python3.8/site-packages/antlr4/tree/Tree.py", line 167, in exitRule
#     ctx.exitRule(listener)
#   File "env/lib/python3.8/site-packages/pymoca/generated/ModelicaParser.py", line 6608, in exitRule
#     listener.exitPrimary_function(self)
#   File "env/lib/python3.8/site-packages/pymoca/parser.py", line 454, in exitPrimary_function
#     for x in ctx.function_call_args().function_arguments().function_argument()]
# AttributeError: 'NoneType' object has no attribute 'function_argument'



#%% Approach #3: load OpenModelica model -> XML -> parse -> parse fails
model_path = 'openmodelica_model'
os.chdir(model_path)

omc = OMCSessionZMQ()
expressionlist = []
expressionlist.append(r'loadFile("SysSim_ECar.mo")')
expressionlist.append('translateModelXML(SysSim_ECar)')

for expression in expressionlist:
    print("Executing: ", expression)
    res = omc.sendExpression(expression)
    print(res)

xml_txt = open('./SysSim_ECar.xml', 'r').read()
test = parse_xml.parse(xml_txt)

## RESULT:
#     test = parse_xml.parse(xml_txt)
#   File "env/lib/python3.8/site-packages/pymoca/backends/xml/parser.py", line 395, in parse
#     root = parser.parse(model_txt)
#   File "env/lib/python3.8/site-packages/pymoca/backends/xml/parser.py", line 33, in parse
#     return etree.fromstring(xml_file, self._parser)
#   File "src/lxml/etree.pyx", line 3237, in lxml.etree.fromstring
#   File "src/lxml/parser.pxi", line 1896, in lxml.etree._parseMemoryDocument
#   File "src/lxml/parser.pxi", line 1784, in lxml.etree._parseDoc
#   File "src/lxml/parser.pxi", line 1141, in lxml.etree._BaseParser._parseDoc
#   File "src/lxml/parser.pxi", line 615, in lxml.etree._ParserContext._handleParseResultDoc
#   File "src/lxml/parser.pxi", line 725, in lxml.etree._handleParseResult
#   File "src/lxml/parser.pxi", line 654, in lxml.etree._raiseParseError
#   File "<string>", line 0
# lxml.etree.XMLSyntaxError: Element 'OpenModelicaModelDescription': No matching global declaration available for the validation root.


#%% Approach #4: load OpenModelica model -> save Total model -> load -> dump XML DAE -> parse
model_path = 'openmodelica_model'
os.chdir(model_path)

omc = OMCSessionZMQ()
expressionlist = []
expressionlist.append(r'loadFile("SysSim_ECar.mo")')
expressionlist.append('OpenModelica.Scripting.saveTotalModel("SysSim_ECar_total.mo", SysSim_ECar, stripAnnotations=true, stripComments=true)')
expressionlist.append(r'loadFile("SysSim_ECar_total.mo")')
expressionlist.append('OpenModelica.Scripting.dumpXMLDAE(SysSim_ECar_total, translationLevel="flat", fileNamePrefix="SysSim_ECar_total_DAE")')

for expression in expressionlist:
    print("Executing: ", expression)
    res = omc.sendExpression(expression)
    print(res)

xml_txt = open('./SysSim_ECar_total_DAE.xml', 'r').read()
test = parse_xml.parse(xml_txt)

## RESULT:
# Traceback (most recent call last):
#   File "issue.py", line 65, in <module>
#     test = parse_xml.parse(xml_txt)
#   File "env/lib/python3.8/site-packages/pymoca/backends/xml/parser.py", line 395, in parse
#     root = parser.parse(model_txt)
#   File "env/lib/python3.8/site-packages/pymoca/backends/xml/parser.py", line 33, in parse
#     return etree.fromstring(xml_file, self._parser)
#   File "src/lxml/etree.pyx", line 3237, in lxml.etree.fromstring
#   File "src/lxml/parser.pxi", line 1896, in lxml.etree._parseMemoryDocument
#   File "src/lxml/parser.pxi", line 1784, in lxml.etree._parseDoc
#   File "src/lxml/parser.pxi", line 1141, in lxml.etree._BaseParser._parseDoc
#   File "src/lxml/parser.pxi", line 615, in lxml.etree._ParserContext._handleParseResultDoc
#   File "src/lxml/parser.pxi", line 725, in lxml.etree._handleParseResult
#   File "src/lxml/parser.pxi", line 654, in lxml.etree._raiseParseError
#   File "<string>", line 0
# lxml.etree.XMLSyntaxError: Element 'dae': No matching global declaration available for the validation root.


#%% Approach 5: parse .mo file -> generate_xml -> pymoca flatten fails (Trying to set unknown symbol property m)
model_path = 'openmodelica_model'
os.chdir(model_path)

testparse = parse_mo(open('SysSim_ECar_total.mo', 'r').read())
test_xml = generate_xml(testparse, 'SysSim_ECar')

# line 41:16 extraneous input '.' expecting IDENT
# line 42:28 extraneous input '+' expecting {'end', '(', 'der', '{', 'if', '-', 'not', 'false', 'true', '[', 'initial', IDENT, STRING, UNSIGNED_NUMBER}
# line 43:28 extraneous input '+' expecting {'end', '(', 'der', '{', 'if', '-', 'not', 'false', 'true', '[', 'initial', IDENT, STRING, UNSIGNED_NUMBER}
# line 54:16 extraneous input '.' expecting IDENT
# line 77:20 extraneous input '.' expecting IDENT
# line 139:10 no viable alternative at input 'Flange.'
# line 140:15 extraneous input '.' expecting IDENT
# line 238:20 extraneous input '.' expecting IDENT
# line 245:20 extraneous input '.' expecting IDENT
# line 248:10 mismatched input '.' expecting 'end'
# line 249:10 mismatched input '.' expecting 'end'
# line 284:10 no viable alternative at input 'Flange.'
# line 285:15 extraneous input '.' expecting IDENT
# line 301:16 extraneous input '.' expecting IDENT
# line 302:10 mismatched input '.' expecting 'end'
# Traceback (most recent call last):
#   File "issue.py", line 153, in <module>
#     testparse = parse_mo(open('SysSim_ECar_total.mo', 'r').read())
#   File "/env/lib/python3.8/site-packages/pymoca/parser.py", line 770, in parse
#     parse_walker.walk(ast_listener, parse_tree)
#   File "/env/lib/python3.8/site-packages/antlr4/tree/Tree.py", line 151, in walk
#     self.walk(listener, child)
#   File "/env/lib/python3.8/site-packages/antlr4/tree/Tree.py", line 151, in walk
#     self.walk(listener, child)
#   File "/env/lib/python3.8/site-packages/antlr4/tree/Tree.py", line 151, in walk
#     self.walk(listener, child)
#   [Previous line repeated 19 more times]
#   File "/env/lib/python3.8/site-packages/antlr4/tree/Tree.py", line 152, in walk
#     self.exitRule(listener, t)
#   File "/env/lib/python3.8/site-packages/antlr4/tree/Tree.py", line 167, in exitRule
#     ctx.exitRule(listener)
#   File "/env/lib/python3.8/site-packages/pymoca/generated/ModelicaParser.py", line 6608, in exitRule
#     listener.exitPrimary_function(self)
#   File "/env/lib/python3.8/site-packages/pymoca/parser.py", line 454, in exitPrimary_function
#     for x in ctx.function_call_args().function_arguments().function_argument()]
# AttributeError: 'NoneType' object has no attribute 'function_argument'


#%% Approach 6: parse .mo file -> generate_xml -> pymoca flatten fails (Trying to set unknown symbol property m)
model_path = 'total_model'
os.chdir(model_path)

testparse = parse_mo(open('SysSim_ECar_total_mod.mo', 'r').read())
test_xml = generate_xml(testparse, 'SysSim_ECar')

# NOTE: replacing " .Modelica*" with " Modelica*" in file SysSim_ECar_total.mo (see file SysSim_ECar_total_mod.mo) solves the first errors, but not the Traceback:
#     AttributeError: 'NoneType' object has no attribute 'function_argument'
# Traceback (most recent call last):
#   File "issue.py", line 153, in <module>
#     testparse = parse_mo(open('SysSim_ECar_total.mo', 'r').read())
#   File "/env/lib/python3.8/site-packages/pymoca/parser.py", line 770, in parse
#     parse_walker.walk(ast_listener, parse_tree)
#   File "/env/lib/python3.8/site-packages/antlr4/tree/Tree.py", line 151, in walk
#     self.walk(listener, child)
#   File "/env/lib/python3.8/site-packages/antlr4/tree/Tree.py", line 151, in walk
#     self.walk(listener, child)
#   File "/env/lib/python3.8/site-packages/antlr4/tree/Tree.py", line 151, in walk
#     self.walk(listener, child)
#   [Previous line repeated 19 more times]
#   File "/env/lib/python3.8/site-packages/antlr4/tree/Tree.py", line 152, in walk
#     self.exitRule(listener, t)
#   File "/env/lib/python3.8/site-packages/antlr4/tree/Tree.py", line 167, in exitRule
#     ctx.exitRule(listener)
#   File "/env/lib/python3.8/site-packages/pymoca/generated/ModelicaParser.py", line 6608, in exitRule
#     listener.exitPrimary_function(self)
#   File "/env/lib/python3.8/site-packages/pymoca/parser.py", line 454, in exitPrimary_function
#     for x in ctx.function_call_args().function_arguments().function_argument()]
# AttributeError: 'NoneType' object has no attribute 'function_argument'
```

**Comment by jaeandersson** [comment]
@FreyJo Any progress on this? I'm looking at improving the Modelica import capabilities in CasADi in general.

**Comment by kentrutan** [comment]
@jaeandersson I can help with that. I have been working on Modelica coverage and will be submitting some pull requests.

@FreyJo one problem in the total models is `OpenModelica.Internal.Architecture.integerMax()` is not defined. Unfortunately, fixing that leads to other pymoca issues. Clearly it would be nice to have some more context from pymoca to help you with your workarounds.

**Comment by jaeandersson** [comment]
There is an ongoing effort to standardize "Flat Modelica" in the Modelica consortium in general and newest OpenModelica has a prototype for that. So that could be an alternative to XML maybe? Please send me an email if you want to discuss this further.

**Comment by kentrutan** [comment]
I was really referring to helping on the frontend to improve Modelica language coverage. Hopefully someone else can help with the backend though I may be able to sprinkle in some backend work here and there. I'll send you an email.
