### ISSUE TITLE
Problem with parameters initialized using different parameter

### ISSUE THREAD

**Issue by dospes** [pymoca/pymoca#259]
When initializing parameters in an MO file, these parameters can be assigned starting values like so:
`parameter Real t1 = 2.0;`
Also, parameter values can be assigned by referencing already defined and initialized parameters like so:
`parameter Real t2 = t1;`
In this case, the parser generates a tree with the symbol t2 having a value with the name "t1" but no actual value. It also does not generate an equation for this relation, like it would for a variable (even if this equation is defined in the header section of the MO file and not in the equation section). I'm not sure if this behavior is intended, but it results in issues when using the sympy backend, where this results in a dictionary entry for the parameter that has no value assigned, thus raising a SyntaxError exception:
```
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm 2021.3.1\plugins\python\helpers\pydev\pydevd.py", line 1496, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm 2021.3.1\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:\Users\dospes\Documents\rst_work\modelica\ompython\pymoca_issue.py", line 20, in <module>
    exec(src_code)
  File "<string>", line 36
    t2 : ,
         ^
SyntaxError: invalid syntax
```

I have attached a (non-) working example.
[issue.zip](https://github.com/pymoca/pymoca/files/10228965/issue.zip)

**Comment by jackvreeken** [comment]
That is intended behavior, as downstream applications might want to change the value of `t1` (and expect the value of `t2` to change as well as a result). And parameters are definitely not (state) variables, so there should be no equations generated. 

I think it all works fine for the CasADi backend (you can resolve symbolic values to their numerical values for CasADi with the `resolve_parameter_values` option if you really want). You have been warned before about the SymPy backend being rather scaffoldy, so I won't do it again ;)

**Comment by dospes** [comment]
Alright, thank you for the answer. Do you want me to stop opening issues concerning the sympy backend? I thought it would be good to have some documentation of issues that do not work with the sympy backend, so that the problems do not have to be rediscovered later, should someone try to improve the backend.

**Comment by jackvreeken** [comment]
I'll leave that to @kentrutan . If he's OK with you opening issues for all kind of stuff, I'd at least suggest tagging them with SymPy so they can be easily grouped (and filtered out).

**Comment by kentrutan** [comment]
I'm OK with documenting issues. Maybe someone will step up to address them. My priority is the Modelica Compiler project.
