### ISSUE TITLE
CasADi IVP example

### ISSUE THREAD

**Issue by tsbertalan** [pymoca/pymoca#331]
Can we get a simple example of solving an IVP with the Casadi backend? The one existing example of solving an actual DAE by collocation is overkill for my purposes, and yet it's not clear how to simplify it to forward integration of an ODE.

**Comment by tsbertalan** [comment]
To be concrete, here's a little example I'm trying to build up:

tank_tiny.mo:
```modelica
model TinyTank
    Real volume "Volume of the tank in mL";
    Real port "Flow in (+) or out (-) of the tank in mL/min";
equation
    der(volume) = port;
end TinyTank;

model TinyPump
    parameter Real rpm "Revolutions per minute of the pump";
    parameter Real discharge_amount "Amount of fluid discharged in mL/rev";
    Real inlet_flow "Flow rate into the pump in mL/min";
    Real outlet_flow "Flow rate out of the pump in mL/min";
equation
    inlet_flow = -outlet_flow;
    outlet_flow = rpm * discharge_amount;
end TinyPump;

model TinySystem
    TinyTank tank(volume=100);
    TinyPump pump(rpm=2, discharge_amount=0.1);
equation
    connect(pump.outlet_flow, tank.port);
end TinySystem;
```

and this script to try to use it tanks_mo_run.py:
```python
import pymoca.backends.casadi.api as pymoca_api, numpy as np
import os, sys

HERE = os.path.dirname(os.path.abspath(__file__))

# Specify the path to your Modelica .mo file and the model name
model_folder = HERE
model_name = 'TinySystem'

# Load the model
model = pymoca_api.transfer_model(model_folder, model_name)

import casadi as ca

# Define the time span for the simulation
t0 = 0
tf = 10
N = 100
t = ca.MX.sym('t')

# Define the initial conditions and parameters

x0 = [.1, .6]
parameters = [
    {
        'pump.rpm': 0.5,
        'pump.discharge_amount': 0.47,
    }[str(param)]
    for param in model.parameters
]

# Use CasADi to evaluate the ODE.
dae = model.dae_residual_function
assert dae is not None

# This DAE residual function is a little mysterious, but I belive it's seven arguments are:
#  i0           time
#  i1[D]        state (see model.states)
#  i2[D]        state derivatives (see model.der_states)
#  i3[n_alg]    algebraic variables (see model.alg_states)
#  i4[0]        maybe outputs, of which I have none (see model.outputs) (can just pass ca.Mx())
#  i5[0]        maybe inputs, of which I have none (see model.inputs) (can just pass ca.Mx())
#  i6[2]        parameters (see model.parameters)
# The output is o0[n_eq], the same length as m odel.equations

# In other words, for a given time and state, maybe we can solve for the der_states
# to evaluate the ODE. Then, we can pass that to an ODE solver.

# def ode(t, x, p):
#     state_derivs = ca.MX.sym('xdot', len(model.der_states))
#     alg_vars = ca.MX.sym('alg_vars', len(model.alg_states))
#     inputs = ca.MX.sym('inputs', 0)
#     outputs = ca.MX.sym('outputs', 0)
#     res = dae(t, x, state_derivs, alg_vars, outputs, inputs, p)
#     nlp = {'x': state_derivs, 'f': res}
#     # Solve this somehow
#     return state_derivs_numeric

# Or, I can try to adapt the exponential example:
# Discretization steps
N = 10
D = len(model.states)
n_inp = len(model.inputs)
n_out = len(model.outputs)
n_alg = len(model.alg_states)
n_eq = len(model.equations)

N_to_solve = D * N

# Discretization time step
dt = 0.1

# Optimization variables and bounds
X = ca.MX.sym('X', N_to_solve)
lbX = np.full(N_to_solve, -np.inf)
ubX = np.full(N_to_solve, np.inf)

U = ca.MX.sym('U', N)
lbU = np.full(n_inp, 0)
ubU = np.full(n_inp, 1.75)

# Collocate DAE using backwards Euler method
g = []
i = 0
# res = dae(0, X[0], (X[0] - X0) / dt, U[0], U[i], ca.MX(), ca.MX())

res = dae(
    # i0       time
    0,
    # i1[D]    state (see model.states)
    X[:D],
    # i2[D]    state derivatives (see model.der_states)
    (X[:D] - x0) / dt,
    # i3[n_alg]   algebraic variables (see model.alg_states)
    ca.MX(n_alg, 1),
    # i4[0]    maybe outputs, of which I have none (see model.outputs) (can just pass ca.Mx())
    ca.MX(),
    # i5[0]    maybe inputs, of which I have none (see model.inputs) (can just pass ca.Mx())
    ca.MX(),
    # i6[2]    parameters (see model.parameters)
    parameters,
)
g.append(res)
Xis = [
    X[i * D:(i + 1) * D]
    for i in range(1, N)
]
for i in range(1, N):
    Xi = Xis[i]
    Xim1 = Xis[i - 1]
    res = dae(i * dt, Xi, (Xi - Xim1) / dt, ca.MX(n_alg, 1), ca.MX(), ca.MX(), parameters)
    g.append(res)
    
# Optimization objective
# TODO: Adapt this part--I have no objective, just forward simulation for now.
f = (X[-1] - 1.0)**2

# Solve NLP
nlp = {'x': ca.vertcat(X, U), 'f': f, 'g': ca.vertcat(*g)}
ipopt_options = {'tol': 1e-6}
solver = ca.nlpsol('nlp', 'ipopt', nlp, {'ipopt': ipopt_options})
solution = solver(lbx=ca.vertcat(lbX, lbU), ubx=ca.vertcat(ubX, ubU), lbg=0, ubg=0)

# Plot solution
import matplotlib.pyplot as plt
T = np.linspace(0, N * dt, N + 1)
X = solution['x'][0:N]
U = solution['x'][N:2*N]
plt.plot(T, ca.vertcat(X0, X), label="$x$")
plt.plot(T[1:], U, label="$u$")
plt.legend()
```

This dies on the first call to `dae`:
```
System is not balanced.  Number of states is 4, number of equations is 5.
Traceback (most recent call last):
  File "c:\Users\tsbertalan\Dropbox\Projects\SceneGrammar\src\tranks_mo_run.py", line 87, in <module>
    res = dae(
          ^^^^
  File "C:\Users\tsbertalan\.virtualenvs\scenegrammar\Lib\site-packages\casadi\casadi.py", line 23373, in __call__
    ret = self.call(args)
          ^^^^^^^^^^^^^^^
  File "C:\Users\tsbertalan\.virtualenvs\scenegrammar\Lib\site-packages\casadi\casadi.py", line 20031, in call    
    return _casadi.Function_call(self, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Error in Function::call for 'dae_residual' [MXFunction] at .../casadi/core/function.cpp:379:
.../casadi/core/function_internal.hpp:1649: Input 2 (i2) has mismatching shape. Got 2-by-1. Allowed dimensions, in general, are:
 - The input dimension N-by-M (here 1-by-1)
 - A scalar, i.e. 1-by-1
 - M-by-N if N=1 or M=1 (i.e. a transposed vector)
 - N-by-M1 if K*M1=M for some K (argument repeated horizontally)
 - N-by-P*M, indicating evaluation with multiple arguments (P must be a multiple of 1 for consistency with previous inputs)
  ```

**Comment by jackvreeken** [comment]
The simulation code that I know of is https://gitlab.com/deltares/rtc-tools/-/blob/master/src/rtctools/simulation/simulation_problem.py?ref_type=heads , where `ca.rootfinder` is used. Maybe you can draw inspiration from that?

That said, I would also recommend looking into `ca.integrator` (not used in the code linked above). The DAE -> ODE transition is _far_ from trivial in the general case, but CasADi is supposed to have some sort of index reduction now. I have seen no implementations using Pymoca + CasADi integrator unfortunately, but would be very interested in seeing one!

**Comment by tsbertalan** [comment]
Ok, I think I worked it out, with either our own explicit stepper or `ca.integrator`. Let me know if the below evinces any major misconceptions in how pymoca and casadi work together:

```python
import os
import casadi as ca
import numpy as np
import pymoca.backends.casadi.api as pymoca_api


class Simulator:
    def __init__(self, model_folder, model_name):
        self.model_folder = model_folder
        self.model_name = model_name
        self.model = pymoca_api.transfer_model(model_folder, model_name)
        self.get_dae = self.model.dae_residual_function
        if self.get_dae is None:
            raise RuntimeError("DAE residual function not found in the model.")

        # An integrator in CasADi is a function that takes the state
        # at the initial time x0, a set of parameters p and controls u,
        # and a guess for the algebraic variables (only for DAEs) z0
        # and returns the state vector xf, algebraic variables zf
        # and the quadrature state qf at a number of output times.
        # The control vector u is assumed to be piecewise constant
        # and has the same grid discretization as the output grid.
        #
        # This doesn't work directly--all the integrator interfaces assume
        # We have expressions for the RHS explicitly, which we don't yet have.

        # instead, we'll do a nonlinear rootfinding problem. It has structure
        #  g0(z, x1, ..., xn) = 0
        #  g1(z, x1, ..., xn) = yn
        #  ...
        #  gm(z, x1, ..., xn) = ym
        # where the first equation uniquely defines z as a function of x1, ..., xn
        # by the implicit function theorem and the remaining equations define
        # the auxiliary outputs y1, ..., ym.

        self.n_states = len(self.model.states)
        self.n_params = len(self.model.parameters)
        self.n_der_states = len(self.model.der_states)
        assert self.n_states == self.n_der_states
        self.n_alg_states = len(self.model.alg_states)

        x = ca.MX.sym("x", self.n_states)
        t = ca.MX.sym("t")
        p = ca.MX.sym("p", self.n_params)
        xdot = ca.MX.sym("xdot", self.n_der_states)
        alg_vars = ca.MX.sym("alg_vars", self.n_alg_states)

        # Because we don't have explicit equations for our state derivatives,
        # we'll need to combine them with the algebraic variables
        # in to the implicit part z.
        z = ca.vertcat(alg_vars, xdot)
        dae = self.get_dae(t, x, xdot, alg_vars, ca.MX(), ca.MX(), p)
        g = ca.Function('g', [z, x, p, t], [dae, alg_vars, xdot])
        G = ca.rootfinder('G', 'newton', g)

        self.G = G

    def get_rhs(self, parameters):
        # Make a little closure RHS.
        class RHSClosure:

            def __init__(s, G, parameters, n_alg, n_state):
                s.G = G
                if not isinstance(parameters, (ca.DM, ca.MX, ca.SX)):
                    parameters = ca.DM(parameters)
                s.parameters = parameters
                s.alg_guess = ca.DM([1.0] * n_alg)
                s.xdot_guess = ca.DM([1.0] * n_state)

            def __call__(s, t, x):
                z_guess = ca.vertcat(s.alg_guess, s.xdot_guess)
                _, alg_res, xdot_res = s.G(z_guess, x, s.parameters, t)
                s.alg_guess = alg_res
                s.xdot_guess = xdot_res
                return xdot_res

        # This can be evaluated numerically e.g. on initial conditions like this:
        # xdot_res = rhs(self.t0, self.x0)
            
        return RHSClosure(self.G, parameters, len(self.model.alg_states), len(self.model.states))

    def get_integrator(self, t0=0, tf=1.0, N=1, method='cvodes'):
        parameters = ca.MX.sym('p', self.n_params)
        rhs = self.get_rhs(parameters)
        x = ca.MX.sym('x', self.n_states)
        t = ca.MX.sym('t')
        integrator_args = {
            'x': x,
            'p': parameters,
            't': t,
            'ode': rhs(t, x),
        }

        T = np.linspace(t0, tf, N)
        return ca.integrator('F', 'cvodes', integrator_args, t0, T)

    def simulate_rk(self, t0, tf, N, x0, parameters, as_numpy=True):
        rhs = self.get_rhs(parameters)
        t0 = float(t0)
        tf = float(tf)
        N = N
        dt = (tf - t0) / N

        # Here, I'll just put this into an explicit Runge-Kutta.
        # However, it's also possible to feed this into the ca.integrator
        # Either way, I do belive that the solution is still differentiable w.r.t. inputs, which is nice.
        result = []
        dt = ca.DM(dt)
        t = ca.DM(t0)
        x = ca.DM(x0)

        T = []
        X = []
        for _ in range(N):
            T.append(t)
            X.append(x)
            k1 = rhs(t, x)
            k2 = rhs(t + dt/2, x + dt/2 * k1)
            k3 = rhs(t + dt/2, x + dt/2 * k2)
            k4 = rhs(t + dt, x + dt * k3)
            x = x + dt/6 * (k1 + 2*k2 + 2*k3 + k4)
            t += dt

        T.append(t)
        X.append(x)

        if as_numpy:
            T, X = np.vstack(T), np.vstack(X)
        return T, X
    
    def simulate(self, t0, tf, N, x0, parameters, as_numpy=True):
        N += 1  # code .get_integrator thinks of N as number of timepoints,
        # but we want it to have been number of steps.
        integrator = self.get_integrator(t0=t0, tf=tf, N=N)
        results = integrator(x0=x0, p=parameters)
        T = np.linspace(t0, tf, N)
        xf = results['xf']
        if as_numpy:
            xf = np.array(xf)
        return T, xf


if __name__ == "__main__":
    model_folder = os.path.dirname(os.path.abspath(__file__))
    model_name = 'TinySystem'

    simulator = Simulator(model_folder, model_name)
    sim_kw = dict(
        t0=0, tf=10, N=100, 
        x0=[0.1], 
        parameters=[0.5, 0.47]
    )
    T_rk, X_rk = simulator.simulate_rk(**sim_kw)
    T, X = simulator.simulate(**sim_kw)

    import matplotlib.pyplot as plt
    fig, ax = plt.subplots()
    ax.plot(T, X.T)
    ax.set_xlabel('$t$')
    ax.set_ylabel(r'$\vec{x}$')
    fig.tight_layout()
    fig.savefig(
        os.path.join(
            model_folder,
            model_name+'.png'
        )
    )

```

**Comment by awecefil** [comment]
Hi @tsbertalan, thanks for giving such CasADi IVP example. However, when I try to run that example, I got Dimension mismatch error like below:
```
System is not balanced.  Number of states is 4, number of equations is 5.
Traceback (most recent call last):
  File "d:\try-pymoca\casadi_IVP_example.py", line 147, in <module>
    simulator = Simulator(model_folder, model_name)
  File "d:\try-pymoca\casadi_IVP_example.py", line 54, in __init__
    G = ca.rootfinder('G', 'newton', g)
  File "D:\miniforge3\envs\pymoca\lib\site-packages\casadi\casadi.py", line 30645, in rootfinder
    return _casadi.rootfinder(*args)
RuntimeError: .../casadi/core/function_internal.cpp:146: Error calling Newton::init for 'G':
.../casadi/core/rootfinder.cpp:218: Assertion "n_ == oracle_.nnz_in(iin_)" failed:
Dimension mismatch. Input size is 4, while output size is 5
```
Is there anything I miss? My casadi version is 3.6.6
